#!/bin/csh

if ($#argv == 0) then
  echo "ERROR: no batchdir argument supplied"
  exit
endif

set batchdir = ~/batchdirs/$1

if ($#argv > 1) then
  set N = $2
else
  set N = 10
endif

cd $batchdir
mkdir -p pbsout
set joblist = `cat scriptlist.txt`

touch 'pbsout/.isrunning'

foreach job ( $joblist )
  echo $job
  xmajjob $job >& /dev/null &
  sleep 0.3
  while (1)
    sleep 0.2
    set flist = `ls pbsout/.isrunning*`
    if ($#flist <= $N) then
      break
    endif
  end
end

mv 'pbsout/.isrunning' 'pbsout/.finished'

